services:
  - type: web
    name: encuestas-por-voz-client
    env: static
    buildCommand: npm install && CI=false npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
